server:
  port: 9527

spring:
  application:
    name: booksystem-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: book-system-9527-zuul
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept
  #http://localhost:9527/atguigu/mydept/admin/book/bookList
  #前缀url
  prefix: /atguigu
  #禁用服务名访问
  ignored-services: "*"
  #配置服务的url映射
  routes:
    mydept.serviceId: booksystem
    mydept.path: /mydept/**

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

